# SConstruct
# Copyright (C) 1999-2009 Eicke Godehardt

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston,
# MA 02111-1307, USA.

# $Id:$

Import ('env install_dir tar_file')

languages = ['cs', 'de', 'fr']

env.Command ('glosung.pot', ['#/src/about.c',
                             '#/src/glosung.c',
                             '#/src/parser.c'],
             "xgettext --add-comments --keyword=_ --keyword=N_ --add-location --strict --output=$TARGET $SOURCES");
for lang in languages:
    env.Execute (action = "msgmerge --update --strict --verbose " + lang + ".po glosung.pot");
    env.Command (lang + '.mo', lang + '.po',
            "msgfmt --statistics --verbose --strict --check --output=$TARGET $SOURCES");
    env.InstallAs (target = install_dir + '/share/locale/' + lang + '/LC_MESSAGES/glosung.mo',
                  source = lang + '.mo')

if env['PLATFORM'] != 'win32':
	env.Tar (tar_file, ['SConscript',
                    'cs.po',
                    'fr.po',
                    'de.po'])

#msgmerge --update --strict --verbose de.po glosung.pot
